# Server Configuration
server:
  fastapi:
    host: "0.0.0.0"
    port: 8080
    reload: true
  streamlit:
    host: "0.0.0.0"
    port: 8502

# API Configuration
api:
  base_url: "http://localhost:8080"
  endpoints:
    generate_script: "/generate-script"

# Model Configuration
model:
  name: "gpt2"
  cache_dir: ".model_cache"
  parameters:
    max_length: 800
    min_length: 300
    temperature: 0.7
    top_p: 0.9
    top_k: 50
    repetition_penalty: 1.2

# File Configuration
file:
  allowed_extensions: ["docx"]
  temp_dir: "temp"
