apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-summarization
  labels:
    app: resume-summarization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-summarization
  template:
    metadata:
      labels:
        app: resume-summarization
    spec:
      containers:
      - name: resume-summarization
        image: tsgroup0555/resume-summarization:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: api
        - containerPort: 8502
          name: ui
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: CLEARML_API_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: clearml-credentials
              key: access_key
        - name: CLEARML_API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: clearml-credentials
              key: secret_key
        - name: CLEARML_API_HOST
          value: "https://api.clear.ml"
        - name: CLEARML_WEB_HOST
          value: "https://app.clear.ml"
        - name: CLEARML_FILES_HOST
          value: "https://files.clear.ml"
