apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-video-generator
  labels:
    app: resume-video-generator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resume-video-generator
  template:
    metadata:
      labels:
        app: resume-video-generator
    spec:
      containers:
      - name: resume-video-generator
        image: ${DOCKER_HUB_USERNAME}/resume-video-generator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: api
        - containerPort: 8502
          name: ui
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: resume-config
              key: model_path
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: resume-config
              key: api_url
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
          readOnly: true
        - name: template-storage
          mountPath: /app/src/templates
          readOnly: true
        readinessProbe:
          httpGet:
            path: /health
            port: api
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: api
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-pvc
      - name: template-storage
        configMap:
          name: template-config
