apiVersion: v1
kind: Secret
metadata:
  name: clearml-credentials
type: Opaque
stringData:
  access_key: ${CLEARML_API_ACCESS_KEY}
  secret_key: ${CLEARML_API_SECRET_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config
type: Opaque
stringData:
  docker_user: ${DOCKER_USER}
