apiVersion: v1
kind: Service
metadata:
  name: resume-summary-service
spec:
  selector:
    app: resume-summary
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: ui
      protocol: TCP
      port: 8501
      targetPort: 8501
  type: LoadBalancer
