apiVersion: v1
kind: Service
metadata:
  name: resume-summarization
  labels:
    app: resume-summarization
spec:
  selector:
    app: resume-summarization
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: ui
      protocol: TCP
      port: 8502
      targetPort: 8502
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
