apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: template-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Smaller size as templates are small
  storageClassName: standard
