name: CD Pipeline

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker pull $DOCKER_USER/resume-summarization:latest
    
      - name: Delete Old Docker Container
        run: sudo docker rm -f resume-summarization-api-container || true
    
      - name: Run Docker Container
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker run -it -d -p 8080:8080 -p 8502:8502 --name resume-summarization-api-container $DOCKER_USER/resume-summarization:latest