name: CI Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
  CLEARML_API_SECRET_KEY: ${{ secrets.CLEARML_API_SECRET_KEY }}
  CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
  CLEARML_FILES_HOST: ${{ secrets.CLEARML_FILES_HOST }}

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true  # Make linting optional
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"  # Install package with development dependencies
    
    - name: Run linting
      run: |
        black . --check
        isort . --check
        flake8 .

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"  # Install package with development dependencies
    
    - name: Configure ClearML
      run: |
        mkdir -p ~/.clearml
        echo "api {
            web_server: $CLEARML_API_HOST
            api_server: $CLEARML_API_HOST
            files_server: $CLEARML_FILES_HOST
            credentials {
                access_key: $CLEARML_API_ACCESS_KEY
                secret_key: $CLEARML_API_SECRET_KEY
            }
        }" > ~/.clearml/config.txt
    
    - name: Add src to PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV
    
    - name: Test with pytest
      run: pytest --cov=src --cov-report=xml
    
    # - name: Upload coverage reports to Codecov
    #   uses: codecov/codecov-action@v3
    #   env:
    #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    #   with:
    #     file: ./coverage.xml
    #     fail_ci_if_error: true

  build:
    needs: [test]  # Only depends on test job, not lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Build package
      run: |
        pip install build
        python -m build
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/

  push-image:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v3
    
    - name: Login to Docker hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Build the Docker image for Fastapi app
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
      run: docker build . -f Dockerfile -t $DOCKER_USER/resume-summarization:latest

    - name: Push the Docker Image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
      run: docker push $DOCKER_USER/resume-summarization

    - name: Logout to Docker hub
      run: docker logout
